name: tests

on:
  push:
  pull_request:

jobs:
  scenario-tests:
    runs-on: ubuntu-latest
    container: ghcr.io/plc-lang/rusty:master-x86_64
    steps:
      - uses: actions/checkout@v4
      - name: Build with RuSTy and run scenario tests
        run: sh tests/run.sh
